version: "3.8"

services:
  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

volumes:
  mongo_data:
  mongo_config:
